version: '2'

services:
  redis:
    restart: always
    image: redis:3-alpine
    volumes:
    - ./data/redis:/data:Z

  mysql:
    restart: always
    image: mysql:5.7
    volumes:
    - ./data/mysql:/var/lib/mysql:Z
    - ./init_sql.sh:/docker-entrypoint-initdb.d/10-init_sql.sh
    - ./pybbs/pybbs.sql:/pybbs.sql
    volumes_from:
    - data
    command: --character-set-server=utf8
    environment:
    - MYSQL_ROOT_PASSWORD=123123

  data:
    image: mysql:5.7
    volumes:
    - ./data/init/:/init/
    command: mkdir -m 0777 /init/mysql

  tomcat:
    restart: always
    image: tomcat:8-jre8
    depends_on:
    - mysql 
    - redis
    volumes_from:
    - data
    ports:
    - "8080:8080"
    links:
    - mysql:mysql
    - redis:redis
    volumes:
    - ./server.xml:/usr/local/tomcat/conf/server.xml:Z
    - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:Z
    - ./pybbs/target/pybbs.war:/usr/local/tomcat/webapps/ROOT.war
    - ./run.sh:/usr/local/tomcat/bin/run.sh
    command: run.sh


